services:
  worker:
    image: lagrangelabs/worker:latest
    container_name: worker
    environment:
    ###################################
    #Setup variables###################
    # You can find the list of the public RPCs for holesky here https://chainlist.org/chain/17000
    - RPC_URL=https://ethereum-holesky-rpc.publicnode.com
    - AVS__ETH_PWD=${AVS__ETH_PWD}
    - AVS__ETH_KEYSTORE=/config/priv_key.json
    # set Network to holesky for testnet
    - NETWORK=mainnet
    ###################################
    - AVS__LAGR_KEYSTORE=/config/lagr_keystore.json
    - AVS__LAGR_PWD=${AVS__LAGR_PWD}
    - RUST_LOG=info,worker=debug
    - PUBLIC_PARAMS__SKIP_STORE=false
    ports:
      - "9090:9090"
    volumes:
      - ./config:/config
      - ./zkmr_params:/zkmr_params
    restart: always
    pull_policy: always
    command: ["worker", "--config", "/config/worker-conf.toml"]
