version: '3.8'

services:
  worker:
    image: lagrangelabs/worker:latest
    container_name: worker
    environment:
    ###################################
    #Remove this after setup############
    - RPC_URL=${RPC_URL}
    - AVS__ETH_PWD=${AVS__ETH_PWD}
    - AVS__ETH_KEYSTORE=/config/priv_key.json
    - NETWORK=holesky
    ###################################
    - AVS__LAGR_KEYSTORE=/config/lagr_keystore.json
    - AVS__LAGR_PWD=${AVS__LAGR_PWD}
    - RUST_LOG=info,worker=debug
    - PUBLIC_PARAMS__SKIP_STORE=false
    ports:
      - "9090:9090"
    volumes:
      - ./config:/config
      - ./zkmr_params:/zkmr_params
    restart: always
    pull_policy: always
    command: ["worker", "--config", "/config/worker-conf.toml"]