version: '3.8'

services:
  worker:
    image: lagrangelabs/worker:develop
    container_name: worker
    environment:
    - ETHEREUM__URL=${ETHEREUM__URL}
    - AVS__KEYSTORE_PATH=${AVS__KEYSTORE_PATH}
    - AVS__KEYSTORE_PASSWORD=${AVS__KEYSTORE_PASSWORD}
    ports:
      - "9090:9090"
    volumes:
      - ./config:/config
    restart: always
    pull_policy: always
    command: ["worker", "--config", "/config/worker-conf.toml"]
