[worker]
# Possible values are ["small","medium","large"]
instance_type = "medium"

[avs]
# for testnet, use:
gateway_url = "http://a2d5e507a3397433490d96c674eb51b7-b2a8d19e1bd1fd40.elb.us-east-2.amazonaws.com:10000"
# for mainnet, use:
# gateway_url = "https://gateway-grpc-mainnet-distributed-query.distributed-query.io"

#This is the operator name. Please change it to your own operator name
issuer = "lagrange"
#This is a display name for your worker. please change it.
worker_id = "CHANGE_THIS_TO_YOUR_WORKER_NAME"

[public_params]
params_root_url = "https://pub-d7c7f0d6979a41f2b25137eaecf12d7b.r2.dev"
dir = "./zkmr_params"

[prometheus]
port = 9090
