[worker]
# Possible values are ["small","medium","large"]
instance_type = "medium"

[avs]
# for testnet, use:
gateway_url = "https://gateway-grpc-testnet-distributed-query-hetzner.testnet.prod.platform.distributed-query.io"
# for mainnet, use:
# gateway_url = "http://a271e1220fa8d4c62aedb5f0e59c6fe3-61018af36abe1235.elb.us-east-2.amazonaws.com:10000"

#This is the operator name. Please change it to your own operator name
issuer = "lagrange"
#This is a display name for your worker. please change it.
worker_id = "CHANGE_THIS_TO_YOUR_WORKER_NAME"

[public_params]
params_root_url = "https://public-parameters.distributed-query.io"
dir = "./zkmr_params"

[prometheus]
port = 9090
